language: node_js
node_js:
  - "9.11.1"

jobs:
  include:
    - stage: Test
      before_install:
        - cd app
      cache: npm
      script: npm test
    - stage: Deploy
      before_install:
        - ./install-wine.sh
        - cd app
      sudo: required
      cache: npm
        # - npm install
      script: npm run deploy
      on:
        branch: master