language: node_js
node_js:
  - "9.11.1"

jobs:
  include:
    - stage: Test
      cache:
        directories:
          - app/node_module
      before_install:
        - cd app
      script: npm test
    - stage: Deploy
      cache:
        directories:
          - app/node_module
          - wine
      before_install:
        - ./install-wine.sh
        - cd app
      sudo: required
      script: npm run deploy
      on:
        branch: master