osx_image: xcode10.1
dist: trusty
sudo: false

language: node_js
node_js: "9.11.1"


before_install:
  - cd app

jobs:
  include:
    - stage: Test
      script: npm test
    - stage: Deploy
      matrix:
        include:
        - name: windows & Mac
          env:
            global:
            - ELECTRON_CACHE=$HOME/.cache/electron
            - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
          os: osx
          cache:
            directories:
            - app/node_modules
            - $HOME/.cache/electron
            - $HOME/.cache/electron-builder
            - $HOME/.npm/_prebuilds
          script:
          -  npm run release -- --mac --win
          before_cache:
          - rm -rf $HOME/.cache/electron-builder/wine
          on:
            branch: master
        - name: linux
          env:
            global:
            - ELECTRON_CACHE=$HOME/.cache/electron
            - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
          os: linux
          cache:
            directories:
            - app/node_modules
            - $HOME/.cache/electron
            - $HOME/.cache/electron-builder
            - $HOME/.npm/_prebuilds
          script:
          -  npm run release
          on:
            branch: master

