sudo: false

language: node_js
node_js: "9.11.1"

before_install:
  - cd app

cache:
  directories:
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Test
      script: 
        - npm test
        - sh .travis-update-app-package-version.sh
    - stage: Deploy Windows & Mac
      os: osx
      osx_image: xcode10.1
      script:
        -  npm run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      on:
        tags: true
    - stage: Deploy linux
      os: linux
      dist: trusty
      script:
        -  npm run release
      on:
        tags: true

