name: qr-code-generator-desktop
version: 1.0
summary: Qr Code Generator
description: Create custom QR Codes. You can save them as PNG image. You can change the size of the image.

confinement: strict
grade: devel

parts:
  electron-app:
    source: app/
    plugin: nodejs
    node-engine: 9.11.1

    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
      - libappindicator1
      - libsecret-1-0
      - libgtk-3-dev
    after:
      - desktop-gtk3
    build: npm run pack
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      cd release-builds/*/
      mv * $SNAPCRAFT_PART_INSTALL/app
    stage:
      - -lib/node_modules
    prime:
      - -node_modules
 
apps:
  qr-code-generator-desktop:
    command: desktop-launch $SNAP/app/qr-code-generator-desktop
    plugs:
      - home 
      - desktop 
      - desktop-legacy 
      - x11 
      - unity7
      - wayland 
      - browser-support 
      - network 
      - gsettings 
      - pulseaudio 
      - opengl

    environment:
      TMPDIR: $XDG_RUNTIME_DIR
