name: qr-code-generator-desktop
version: 1.0
summary: Qr Code Generator
description: This is a minimal Electron application based on the
  Quick Start Guide within the Electron documentation.
confinement: "strict"

apps:
  qr-code-generator-desktop:
    command: desktop-launch $SNAP/qr-code-generator-desktop.wrapper
    plugs:
     - browser-support
     - network
     - unity7
     - gsettings
     # - home
     # - pulseaudio
     # - opengl

parts:
  electron-app:
    source: app/
    plugin: nodejs

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio

    after:
      - desktop-gtk2
  deps:
    plugin: nil
    stage-packages:
      - libgconf-2-4
      - libnss3
      - libxss1
      - fontconfig-config

  desktop-integration:
    plugin: nil
    stage-packages:
      - libappindicator1
      - libdbusmenu-glib4
      - libnotify4
      - libunity9

  launcher:
    plugin: copy
    files:
      qr-code-generator-desktop: qr-code-generator-desktop.wrapper
    after: [desktop-glib-only]
