name: qr-code-generator-desktop
version: 1.0
summary: Qr Code Generator
description: Create custom QR Codes. You can save them as PNG image. You can change the size of the image.

confinement: strict
grade: stable

parts:
  electron-app:
    source: app/
    plugin: nodejs
    node-engine: 9.11.1

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
      - libdb5.3

    after:
      - desktop-gtk2
    build: npm run pack
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      cd release-builds/*/
      mv * $SNAPCRAFT_PART_INSTALL/app
    stage:
      - -lib/node_modules
    prime:
      - -node_modules
 
apps:
  qr-code-generator-desktop:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/app/qr-code-generator-desktop
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
