name: qr-code-generator-desktop
version: 1.0
summary: Qr Code Generator
description: This is a minimal Electron application based on the
  Quick Start Guide within the Electron documentation.

confinement: strict
grade: stable

parts:
  electron-app:
    source: .
    plugin: nodejs
    node-engine: 10.15.3

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - libdb-dev
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio

    after:
      - desktop-gtk2
    build: npm run pack
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv release-builds/`ls release-builds`/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules
 
apps:
  qr-code-generator-desktop:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/app/qr-code-generator-desktop
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
